### ISSUE TITLE
Code and Design review

### ISSUE THREAD

**Issue by zoepje** [Patrickkhr/dont-repeat-yourself-component-library#1]
### Buttons
<img width="371" alt="Screenshot 2024-11-15 at 2 20 36 PM" src="https://github.com/user-attachments/assets/1dd92fc5-16e0-4b1d-bd47-ed25888fe0fd">

Het kleur contrast hier is niet goed 1.9:1 het moet minimaal 4.5:1 zijn. Ik zou de text zwart maken net zoals bij NEW stikker

### Kaartjes
Ik zou qua visuele hierarchie voor het eerste kaartje kiezen. Ik zie namelijk eerst new dan zie ik de plaats en uiteindelijk de boek nu button.

**Comment by Patrickkhr** [comment]
Bedankt voor de feedback we hebben de knop aangepast!
