### ISSUE TITLE
[FORM COMPONENT] DRY

### ISSUE THREAD

**Issue by Seijno** [Patrickkhr/dont-repeat-yourself-component-library#4]
## probleemstelling
Als component werk je aan een form, in je code maak je de form en style je het, maar mocht je op een andere pagina ook een form nodig hebben moet je het opnieuw maken en krijg je een herhaling.

## oplossing
Deel je form inputs op in componenten, deze kan je zien als molocules in het _atom design_. Zo zorg je ervoor dat je later makkelijker een de form krijgt met styling erbij en als je de forms wil aanpassen, dat je dit effectiever doet.

## Bron
Hier een [artikel](https://www.bluebirdday.nl/insights/atomic-design-wat-is-hoe-werkt-het) over Atom design, kijk of je hier gebruik van kan maken :)

**Comment by Patrickkhr** [comment]
Bedankt voor feedback ik heb de inputs ingedeeld in componenten
