### ISSUE TITLE
[FORM PAGE] PE

### ISSUE THREAD

**Issue by Seijno** [Patrickkhr/dont-repeat-yourself-component-library#5]
## Probleem
Na het invullen van de form gebeurd er nog niks. Dit zou een perfect moment zijn om PE toe te passen met een event die afspeelt na het submitten. Hier heb je al wel een design voor gemaakt.

## Oplossing
Kijk wat je kan doen met js, misschien kan je een section laten zien zodra je op submit heb gedrukt?

**Comment by Patrickkhr** [comment]
Bedankt voor de feedback, ik heb loading en succes states toegevoegd!
