### ISSUE TITLE
Title component verschillende headings toevoegen

### ISSUE THREAD

**Issue by Mossati** [Patrickkhr/dont-repeat-yourself-component-library#7]
### Title heading
De Title component heeft nu alleen een H2 element maar probeer het dynamisch te maken voor meerdere heading elementen.

**Comment by TygoWolven** [comment]
Deze issue heb ik behandeld in de repository van mijn deeltaak!
https://github.com/TygoWolven/Sprint16-Component-Building-Block/issues/1
